export declare const taxTypeEnum: import("drizzle-orm/pg-core").PgEnum<["sales_tax", "vat", "gst", "excise", "withholding"]>;
export declare const taxPostingRuleEnum: import("drizzle-orm/pg-core").PgEnum<["output_liability", "input_asset", "expense"]>;
export declare const taxCodes: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "tax_codes";
    schema: undefined;
    columns: {
        code: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        type: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["sales_tax", "vat", "gst", "excise", "withholding"]>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string enum";
            data: "sales_tax" | "vat" | "gst" | "excise" | "withholding";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["sales_tax", "vat", "gst", "excise", "withholding"];
            identity: undefined;
            generated: undefined;
        }>;
        glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        isClaimable: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "boolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        postingRule: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["output_liability", "input_asset", "expense"]>>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string enum";
            data: "expense" | "output_liability" | "input_asset";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["output_liability", "input_asset", "expense"];
            identity: undefined;
            generated: undefined;
        }>;
        isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "boolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTimestampBuilder, {
            name: string;
            tableName: "tax_codes";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "tax_codes";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const taxRates: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "tax_rates";
    schema: undefined;
    columns: {
        taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "tax_rates";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        rate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>, {
            name: string;
            tableName: "tax_rates";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        effectiveDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
            name: string;
            tableName: "tax_rates";
            dataType: "string date";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        expiryDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgDateStringBuilder, {
            name: string;
            tableName: "tax_rates";
            dataType: "string date";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "tax_rates";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
            name: string;
            tableName: "tax_rates";
            dataType: "boolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "tax_rates";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "tax_rates";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "tax_rates";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "tax_rates";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const taxAutoAssignmentRules: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "tax_auto_assignment_rules";
    schema: undefined;
    columns: {
        name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        priority: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgIntegerBuilder>>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "number int32";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        entityType: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        entityCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        customerGroupId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        itemCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        regionCode: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "boolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTimestampBuilder, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "tax_auto_assignment_rules";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const insertTaxCodeSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    code: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    type: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["sales_tax", "vat", "gst", "excise", "withholding"]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string enum";
        data: "sales_tax" | "vat" | "gst" | "excise" | "withholding";
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["sales_tax", "vat", "gst", "excise", "withholding"];
        identity: undefined;
        generated: undefined;
    }>;
    glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isClaimable: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    postingRule: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["output_liability", "input_asset", "expense"]>>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string enum";
        data: "expense" | "output_liability" | "input_asset";
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["output_liability", "input_asset", "expense"];
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, {
    code: (schema: import("zod").ZodString) => import("zod").ZodString;
    name: (schema: import("zod").ZodString) => import("zod").ZodString;
}, undefined>;
export declare const selectTaxCodeSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    code: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    type: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["sales_tax", "vat", "gst", "excise", "withholding"]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string enum";
        data: "sales_tax" | "vat" | "gst" | "excise" | "withholding";
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["sales_tax", "vat", "gst", "excise", "withholding"];
        identity: undefined;
        generated: undefined;
    }>;
    glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isClaimable: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    postingRule: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["output_liability", "input_asset", "expense"]>>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string enum";
        data: "expense" | "output_liability" | "input_asset";
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["output_liability", "input_asset", "expense"];
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateTaxCodeSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    code: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    type: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["sales_tax", "vat", "gst", "excise", "withholding"]>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string enum";
        data: "sales_tax" | "vat" | "gst" | "excise" | "withholding";
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["sales_tax", "vat", "gst", "excise", "withholding"];
        identity: undefined;
        generated: undefined;
    }>;
    glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isClaimable: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    postingRule: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["output_liability", "input_asset", "expense"]>>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string enum";
        data: "expense" | "output_liability" | "input_asset";
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["output_liability", "input_asset", "expense"];
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_codes", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_codes";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const insertTaxRateSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    rate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    effectiveDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    expiryDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgDateStringBuilder, {
        name: string;
        tableName: "tax_rates";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const selectTaxRateSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    rate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    effectiveDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    expiryDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgDateStringBuilder, {
        name: string;
        tableName: "tax_rates";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateTaxRateSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    rate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    effectiveDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    expiryDate: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgDateStringBuilder, {
        name: string;
        tableName: "tax_rates";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_rates", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_rates";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const insertTaxAutoAssignmentRuleSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    priority: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgIntegerBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "number int32";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    entityType: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    entityCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    customerGroupId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    itemCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    regionCode: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, {
    name: (schema: import("zod").ZodString) => import("zod").ZodString;
}, undefined>;
export declare const selectTaxAutoAssignmentRuleSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    priority: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgIntegerBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "number int32";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    entityType: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    entityCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    customerGroupId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    itemCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    regionCode: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateTaxAutoAssignmentRuleSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    name: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    priority: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgIntegerBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "number int32";
        data: number;
        driverParam: string | number;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    taxCodeId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    entityType: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    entityCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    customerGroupId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    itemCategoryId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    regionCode: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    id: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"tax_auto_assignment_rules", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "tax_auto_assignment_rules";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export type TaxCode = typeof taxCodes.$inferSelect;
export type NewTaxCode = typeof taxCodes.$inferInsert;
export type TaxRate = typeof taxRates.$inferSelect;
export type NewTaxRate = typeof taxRates.$inferInsert;
export type TaxAutoAssignmentRule = typeof taxAutoAssignmentRules.$inferSelect;
export type NewTaxAutoAssignmentRule = typeof taxAutoAssignmentRules.$inferInsert;
//# sourceMappingURL=schema.d.ts.map