export declare const budgetHeaders: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "budget_headers";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "budget_headers";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "budget_headers";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTimestampBuilder, {
            name: string;
            tableName: "budget_headers";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        name: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        periodStart: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string date";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        periodEnd: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string date";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        totalAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        status: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
            name: string;
            tableName: "budget_headers";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
            name: string;
            tableName: "budget_headers";
            dataType: "boolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: 'pg';
}>;
export declare const budgetLines: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "budget_lines";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "budget_lines";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "budget_lines";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        budgetHeaderId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        budgetAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        consumedAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        varianceAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
            name: string;
            tableName: "budget_lines";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
            name: string;
            tableName: "budget_lines";
            dataType: "boolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: 'pg';
}>;
export declare const budgetConsumptions: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "budget_consumptions";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        budgetLineId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        journalEntryId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").PgUUIDBuilder, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        amount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        consumptionDate: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
            name: string;
            tableName: "budget_consumptions";
            dataType: "string date";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: 'pg';
}>;
export declare const insertBudgetHeaderSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    periodStart: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    periodEnd: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    totalAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, {
    name: (schema: import("zod").ZodString) => import("zod").ZodString;
}, undefined>;
export declare const selectBudgetHeaderSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    periodStart: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    periodEnd: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    totalAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateBudgetHeaderSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "budget_headers";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    periodStart: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    periodEnd: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    totalAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_headers", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "budget_headers";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const insertBudgetLineSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetHeaderId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    consumedAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    varianceAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const selectBudgetLineSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetHeaderId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    consumedAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    varianceAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateBudgetLineSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetHeaderId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    glAccountId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    consumedAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    varianceAmount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"budget_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "budget_lines";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const insertBudgetConsumptionSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetLineId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    journalEntryId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    amount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    consumptionDate: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const selectBudgetConsumptionSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    budgetLineId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    journalEntryId: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    amount: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    consumptionDate: import("drizzle-orm/pg-core").PgBuildColumn<"budget_consumptions", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "budget_consumptions";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export type BudgetHeader = typeof budgetHeaders.$inferSelect;
export type NewBudgetHeader = typeof budgetHeaders.$inferInsert;
export type BudgetLine = typeof budgetLines.$inferSelect;
export type NewBudgetLine = typeof budgetLines.$inferInsert;
export type BudgetConsumption = typeof budgetConsumptions.$inferSelect;
export type NewBudgetConsumption = typeof budgetConsumptions.$inferInsert;
//# sourceMappingURL=schema.d.ts.map