export declare const accountTypeEnum: import("drizzle-orm/pg-core").PgEnum<["asset", "liability", "equity", "revenue", "expense"]>;
export declare const journalEntryStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "posted", "voided"]>;
export declare const accounts: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "accounts";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "accounts";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "accounts";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "accounts";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgTimestampBuilder, {
            name: string;
            tableName: "accounts";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "accounts";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        code: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "accounts";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        name: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "accounts";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        type: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["asset", "liability", "equity", "revenue", "expense"]>>, {
            name: string;
            tableName: "accounts";
            dataType: "string enum";
            data: "asset" | "equity" | "expense" | "liability" | "revenue";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["asset", "liability", "equity", "revenue", "expense"];
            identity: undefined;
            generated: undefined;
        }>;
        parentId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgUUIDBuilder, {
            name: string;
            tableName: "accounts";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        balance: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
            name: string;
            tableName: "accounts";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        isActive: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
            name: string;
            tableName: "accounts";
            dataType: "boolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: 'pg';
}>;
export declare const journalEntries: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "journal_entries";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "journal_entries";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "journal_entries";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "journal_entries";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgTimestampBuilder, {
            name: string;
            tableName: "journal_entries";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "journal_entries";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        date: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
            name: string;
            tableName: "journal_entries";
            dataType: "string date";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "journal_entries";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        referenceNumber: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "journal_entries";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        status: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["draft", "posted", "voided"]>>>, {
            name: string;
            tableName: "journal_entries";
            dataType: "string enum";
            data: "draft" | "posted" | "voided";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["draft", "posted", "voided"];
            identity: undefined;
            generated: undefined;
        }>;
        createdBy: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "journal_entries";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: 'pg';
}>;
export declare const journalEntryLines: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "journal_entry_lines";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTimestampBuilder, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        journalEntryId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        accountId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        debit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        credit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "string numeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "journal_entry_lines";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: 'pg';
}>;
export declare const fiscalYears: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "fiscal_years";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").PgTimestampBuilder, {
            name: string;
            tableName: "fiscal_years";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        name: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        startDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        endDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        status: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
            name: string;
            tableName: "fiscal_years";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: 'pg';
}>;
export declare const insertAccountSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    code: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    type: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["asset", "liability", "equity", "revenue", "expense"]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string enum";
        data: "asset" | "equity" | "expense" | "liability" | "revenue";
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["asset", "liability", "equity", "revenue", "expense"];
        identity: undefined;
        generated: undefined;
    }>;
    parentId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    balance: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, {
    code: (schema: import("zod").ZodString) => import("zod").ZodString;
    name: (schema: import("zod").ZodString) => import("zod").ZodString;
}, undefined>;
export declare const selectAccountSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    code: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    type: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["asset", "liability", "equity", "revenue", "expense"]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string enum";
        data: "asset" | "equity" | "expense" | "liability" | "revenue";
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["asset", "liability", "equity", "revenue", "expense"];
        identity: undefined;
        generated: undefined;
    }>;
    parentId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    balance: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const insertJournalEntrySchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    date: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    referenceNumber: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["draft", "posted", "voided"]>>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string enum";
        data: "draft" | "posted" | "voided";
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["draft", "posted", "voided"];
        identity: undefined;
        generated: undefined;
    }>;
    createdBy: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const selectJournalEntrySchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    date: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    referenceNumber: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["draft", "posted", "voided"]>>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string enum";
        data: "draft" | "posted" | "voided";
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["draft", "posted", "voided"];
        identity: undefined;
        generated: undefined;
    }>;
    createdBy: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const insertJournalEntryLineSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    journalEntryId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    accountId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    debit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    credit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const selectJournalEntryLineSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    journalEntryId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    accountId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    debit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    credit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const insertFiscalYearSchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    startDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    endDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, {
    name: (schema: import("zod").ZodString) => import("zod").ZodString;
}, undefined>;
export declare const selectFiscalYearSchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    startDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    endDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateAccountSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "accounts";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    code: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    type: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["asset", "liability", "equity", "revenue", "expense"]>>, {
        name: string;
        tableName: "accounts";
        dataType: "string enum";
        data: "asset" | "equity" | "expense" | "liability" | "revenue";
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["asset", "liability", "equity", "revenue", "expense"];
        identity: undefined;
        generated: undefined;
    }>;
    parentId: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "accounts";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    balance: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    isActive: import("drizzle-orm/pg-core").PgBuildColumn<"accounts", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgBooleanBuilder>>, {
        name: string;
        tableName: "accounts";
        dataType: "boolean";
        data: boolean;
        driverParam: boolean;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateJournalEntrySchema: import("drizzle-orm/zod").BuildSchema<"update", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "journal_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    date: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgDateStringBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string date";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    referenceNumber: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgEnumColumnBuilder<["draft", "posted", "voided"]>>>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string enum";
        data: "draft" | "posted" | "voided";
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: ["draft", "posted", "voided"];
        identity: undefined;
        generated: undefined;
    }>;
    createdBy: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateJournalEntryLineSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    journalEntryId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    accountId: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    debit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    credit: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgNumericBuilder>>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string numeric";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    description: import("drizzle-orm/pg-core").PgBuildColumn<"journal_entry_lines", import("drizzle-orm/pg-core").PgTextBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "journal_entry_lines";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const updateFiscalYearSchema: import("drizzle-orm/zod").BuildSchema<"update", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    updatedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    deletedAt: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").PgTimestampBuilder, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    name: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    startDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    endDate: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    status: import("drizzle-orm/pg-core").PgBuildColumn<"fiscal_years", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>>, {
        name: string;
        tableName: "fiscal_years";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;
export type JournalEntry = typeof journalEntries.$inferSelect;
export type NewJournalEntry = typeof journalEntries.$inferInsert;
export type JournalEntryLine = typeof journalEntryLines.$inferSelect;
export type NewJournalEntryLine = typeof journalEntryLines.$inferInsert;
export type FiscalYear = typeof fiscalYears.$inferSelect;
export type NewFiscalYear = typeof fiscalYears.$inferInsert;
//# sourceMappingURL=schema.d.ts.map