export declare const auditLogEntries: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "audit_log_entries";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "object date";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        userId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgUUIDBuilder, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        action: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        resource: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        resourceId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgUUIDBuilder, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string uuid";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        oldValues: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "object json";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        newValues: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "object json";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        ipAddress: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        userAgent: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "string";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
        metadata: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
            name: string;
            tableName: "audit_log_entries";
            dataType: "object json";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            identity: undefined;
            generated: undefined;
        }>;
    };
    dialect: "pg";
}>;
export declare const insertAuditLogEntrySchema: import("drizzle-orm/zod").BuildSchema<"insert", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    userId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    action: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    resource: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    resourceId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    oldValues: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object json";
        data: unknown;
        driverParam: unknown;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    newValues: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object json";
        data: unknown;
        driverParam: unknown;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    ipAddress: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    userAgent: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    metadata: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object json";
        data: unknown;
        driverParam: unknown;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export declare const selectAuditLogEntrySchema: import("drizzle-orm/zod").BuildSchema<"select", {
    id: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetHasRuntimeDefault<import("drizzle-orm/pg-core").SetIsPrimaryKey<import("drizzle-orm/pg-core").PgUUIDBuilder>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    createdAt: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetHasDefault<import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgTimestampBuilder>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object date";
        data: Date;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    userId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    tenantId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgUUIDBuilder>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    action: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    resource: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").SetNotNull<import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    resourceId: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgUUIDBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string uuid";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    oldValues: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object json";
        data: unknown;
        driverParam: unknown;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    newValues: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object json";
        data: unknown;
        driverParam: unknown;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    ipAddress: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    userAgent: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgVarcharBuilder<[string, ...string[]]>, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "string";
        data: string;
        driverParam: string;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
    metadata: import("drizzle-orm/pg-core").PgBuildColumn<"audit_log_entries", import("drizzle-orm/pg-core").PgJsonBuilder, {
        name: string;
        tableName: "audit_log_entries";
        dataType: "object json";
        data: unknown;
        driverParam: unknown;
        notNull: false;
        hasDefault: false;
        isPrimaryKey: false;
        isAutoincrement: false;
        hasRuntimeDefault: false;
        enumValues: undefined;
        identity: undefined;
        generated: undefined;
    }>;
}, undefined, undefined>;
export type AuditLogEntry = typeof auditLogEntries.$inferSelect;
export type NewAuditLogEntry = typeof auditLogEntries.$inferInsert;
//# sourceMappingURL=schema.d.ts.map